Models/Photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.Companies = new HashSet<Company>();
            this.OthBxoes = new HashSet<OthBxo>();
        }
    
        public int photo_id { get; set; }
        public string photo_name { get; set; }
        public Nullable<int> photo_product_id { get; set; }
        public Nullable<int> photo_color_id { get; set; }
        public Nullable<int> photo_type_id { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Mallar Mallar { get; set; }
        public virtual PhotoType PhotoType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OthBxo> OthBxoes { get; set; }
    }
}

Models/PhotoType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoType()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int photo_type_id { get; set; }
        public string photo_type_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}

Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YeniShoppingProject.Models;

namespace YeniShoppingProject.Controllers
{
    public class PhotosController : Controller
    {
        private ShoppingNewEntities1 db = new ShoppingNewEntities1();

        // GET: Photos
        public ActionResult Index()
        {
            var photos = db.Photos.Include(p => p.Color).Include(p => p.Mallar).Include(p => p.PhotoType);
            return View(photos.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            ViewBag.photo_color_id = new SelectList(db.Colors, "color_id", "color_name");
            ViewBag.photo_product_id = new SelectList(db.Mallars, "product_id", "product_name");
            ViewBag.photo_product_id = new SelectList(db.PhotoTypes, "photo_type_id", "photo_type_name");
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Photo photo,HttpPostedFileBase photo_name)
        {
            if (ModelState.IsValid)
            {
                var file_name = Path.GetFileName(photo_name.FileName);
                var src = Path.Combine(Server.MapPath("/Yuklenen"), file_name);
                photo_name.SaveAs(src);
                photo.photo_name = Path.GetFileName(photo_name.FileName);




                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.photo_color_id = new SelectList(db.Colors, "color_id", "color_name", photo.photo_color_id);
            ViewBag.photo_product_id = new SelectList(db.Mallars, "product_id", "product_name", photo.photo_product_id);
            ViewBag.photo_product_id = new SelectList(db.PhotoTypes, "photo_type_id", "photo_type_name", photo.photo_product_id);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.photo_color_id = new SelectList(db.Colors, "color_id", "color_name", photo.photo_color_id);
            ViewBag.photo_product_id = new SelectList(db.Mallars, "product_id", "product_name", photo.photo_product_id);
            ViewBag.photo_product_id = new SelectList(db.PhotoTypes, "photo_type_id", "photo_type_name", photo.photo_product_id);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "photo_id,photo_name,photo_product_id,photo_color_id,photo_type_id")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.photo_color_id = new SelectList(db.Colors, "color_id", "color_name", photo.photo_color_id);
            ViewBag.photo_product_id = new SelectList(db.Mallars, "product_id", "product_name", photo.photo_product_id);
            ViewBag.photo_product_id = new SelectList(db.PhotoTypes, "photo_type_id", "photo_type_name", photo.photo_product_id);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Photos/Create.cshtml
@model YeniShoppingProject.Models.Photo

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Shopi/Views/Shared/_adminLayout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.photo_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_name, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                @Html.ValidationMessageFor(model => model.photo_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_product_id, "photo_product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("photo_product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.photo_product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_color_id, "photo_color_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("photo_color_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.photo_color_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_type_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_type_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Photos/Delete.cshtml
@model YeniShoppingProject.Models.Photo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Shopi/Views/Shared/_adminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photo_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_type_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_type_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.color_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.color_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mallar.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mallar.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoType.photo_type_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoType.photo_type_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Photos/Details.cshtml
@model YeniShoppingProject.Models.Photo

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Shopi/Views/Shared/_adminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photo_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_type_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_type_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.color_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.color_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mallar.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mallar.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoType.photo_type_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoType.photo_type_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.photo_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Photos/Edit.cshtml
@model YeniShoppingProject.Models.Photo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Shopi/Views/Shared/_adminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.photo_id)

        <div class="form-group">
            @Html.LabelFor(model => model.photo_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_product_id, "photo_product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("photo_product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.photo_product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_color_id, "photo_color_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("photo_color_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.photo_color_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_type_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_type_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Photos/Index.cshtml
@model IEnumerable<YeniShoppingProject.Models.Photo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Shopi/Views/Shared/_adminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.photo_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo_type_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color.color_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mallar.product_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoType.photo_type_name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.photo_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.photo_type_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color.color_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mallar.product_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhotoType.photo_type_name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.photo_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.photo_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.photo_id })
        </td>
    </tr>
}

</table>